<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioCheckBatalkanTransaksi</name>
   <tag></tag>
   <elementGuidId>cb150ed5-c07b-4837-b9ee-c5909d287525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='offer_status_cancelled'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'offer_status_cancelled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#statusModal101528 > div.modal-dialog.modal-dialog-centered > form.modal-content.px-4.py-2 > div.modal-body > div.form-check > #offer_status_cancelled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offer_status_cancelled</value>
      <webElementGuid>484eb0c0-65d7-4dd9-8b4c-6192c3860da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='offer_status_cancelled'])[3]</value>
      <webElementGuid>e964ccf5-5e2b-4562-ae65-da5dddcb9e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='statusModal101528']/div/form/div[2]/div[2]/input</value>
      <webElementGuid>f52e8bcd-6cb8-47a3-94d2-7ad72941f9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div[2]/div[2]/input</value>
      <webElementGuid>2c6ac803-e808-4143-8255-e783f7275aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'offer[status]' and @id = 'offer_status_cancelled']</value>
      <webElementGuid>248a4fa7-fb32-4399-ac3f-38039701b01a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
