<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEditProfile</name>
   <tag></tag>
   <elementGuidId>81d2b73c-079a-4eb7-985f-0e0cce92b3af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/user.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/profiles</value>
      <webElementGuid>f0e399cc-43be-4ac8-bc20-0c84728108c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/user.svg</value>
      <webElementGuid>eff71549-fa1f-40e6-bd49-3bd507ac56fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
