<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linkNext</name>
   <tag></tag>
   <elementGuidId>b5ba9d93-bc2d-44b0-adcb-1239b87b2ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'next_page']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div[11]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.next_page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next_page</value>
      <webElementGuid>ed193abf-13ef-4862-a436-e9e7c590938f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div[11]/a[2]</value>
      <webElementGuid>2ea33cea-c3ca-4487-907c-279d736ba570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Next →')]</value>
      <webElementGuid>62b008ef-566b-4991-a340-d4bb59fad4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='← Previous'])[1]/following::a[1]</value>
      <webElementGuid>020743aa-ebcf-4580-a964-4027667df53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 150.000'])[9]/following::a[2]</value>
      <webElementGuid>d6198d1e-567a-4414-ad83-a427d66f8d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jual'])[1]/preceding::a[1]</value>
      <webElementGuid>76af42a4-cf4b-41b4-8a16-916f0ca60a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/?page=3')]</value>
      <webElementGuid>1143ff48-92ed-412f-bb42-b540c2da13d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/a[2]</value>
      <webElementGuid>f3a64b15-f402-4c2b-9748-84fd0bb7f7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/?page=3' and (text() = 'Next →' or . = 'Next →')]</value>
      <webElementGuid>c0cbfe91-7465-4267-a220-7ef872d7a4e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
