<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEditProfile</name>
   <tag></tag>
   <elementGuidId>62e00e3a-e5cb-4e78-b2ff-b1a80cb3d623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'btn btn-outline-primary rounded-4 px-3 ms-auto']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-primary.rounded-4.px-3.ms-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Edit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary rounded-4 px-3 ms-auto</value>
      <webElementGuid>efbce40d-334b-4385-93f7-4e58f1755787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>dcf0396d-0ef0-4f44-a72b-235425ddf3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta'])[2]/following::a[1]</value>
      <webElementGuid>ba020e29-ca1e-44df-8d58-5641f804df7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='penjual'])[2]/following::a[1]</value>
      <webElementGuid>29b60b16-285e-4da6-9212-eebb2652bfa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/preceding::a[1]</value>
      <webElementGuid>a95fb9dd-be70-42ac-aebb-507f1e02e9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Produk'])[1]/preceding::a[1]</value>
      <webElementGuid>9adc434c-882c-4fd0-9b40-46e0d78f3aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>d61d7c8c-ac70-4cac-9c89-a92f8f7e8989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/profiles')])[3]</value>
      <webElementGuid>bc91f6a9-309f-4c75-9f31-6b375d07e532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>68817c06-69de-47bc-81de-7784fadf61c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/profiles' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>ff34e6ab-dfd6-45e0-88e4-f3e00025182e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
