<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>txtProductPrice</name>
   <tag></tag>
   <elementGuidId>a5a28419-d696-4a57-86b5-664ad2ca93df</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>453c8d7f-a0bf-4b59-a1bd-28c205cab2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>id.binar.fp.secondhand:id/tv_product_price</value>
      <webElementGuid>ed4d5b88-13b4-4e68-a1c6-f24c59c1fe92</webElementGuid>
   </webElementProperties>
   <locator>id.binar.fp.secondhand:id/tv_product_price</locator>
   <locatorStrategy>ID</locatorStrategy>
</MobileElementEntity>
