<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>txtBerhasilTawar</name>
   <tag></tag>
   <elementGuidId>a4df83a1-fd0e-4c84-9811-9f92e8c9b98f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>cd4bb225-64db-4e4a-9059-19d6f59ccf16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harga tawarmu berhasil dikirim ke penjual</value>
      <webElementGuid>60d46d4d-def3-4b61-9918-f47acd3689f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>id.binar.fp.secondhand:id/tv_message</value>
      <webElementGuid>137f053d-781a-4c11-8ee1-1251646c4cb8</webElementGuid>
   </webElementProperties>
   <locator>id.binar.fp.secondhand:id/tv_message</locator>
   <locatorStrategy>ID</locatorStrategy>
</MobileElementEntity>
